// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { BingoFieldDefinition } from "./bingo_field_definition_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `BingoFieldDefinitions`.
 *
 * Obtain a handle from the [`bingoFieldDefinitions`] property on [`RemoteTables`],
 * like `ctx.db.bingoFieldDefinitions`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.bingoFieldDefinitions.on_insert(...)`.
 */
export class BingoFieldDefinitionsTableHandle {
  tableCache: TableCache<BingoFieldDefinition>;

  constructor(tableCache: TableCache<BingoFieldDefinition>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<BingoFieldDefinition> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `fieldId` unique index on the table `BingoFieldDefinitions`,
   * which allows point queries on the field of the same name
   * via the [`BingoFieldDefinitionsFieldIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.bingoFieldDefinitions.fieldId().find(...)`.
   *
   * Get a handle on the `fieldId` unique index on the table `BingoFieldDefinitions`.
   */
  fieldId = {
    // Find the subscribed row whose `fieldId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): BingoFieldDefinition | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.fieldId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: BingoFieldDefinition) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: BingoFieldDefinition) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: BingoFieldDefinition) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: BingoFieldDefinition) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: BingoFieldDefinition, newRow: BingoFieldDefinition) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: BingoFieldDefinition, newRow: BingoFieldDefinition) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
