// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { GameSession } from "./game_session_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `GameSessions`.
 *
 * Obtain a handle from the [`gameSessions`] property on [`RemoteTables`],
 * like `ctx.db.gameSessions`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.gameSessions.on_insert(...)`.
 */
export class GameSessionsTableHandle {
  tableCache: TableCache<GameSession>;

  constructor(tableCache: TableCache<GameSession>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<GameSession> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `gameId` unique index on the table `GameSessions`,
   * which allows point queries on the field of the same name
   * via the [`GameSessionsGameIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.gameSessions.gameId().find(...)`.
   *
   * Get a handle on the `gameId` unique index on the table `GameSessions`.
   */
  gameId = {
    // Find the subscribed row whose `gameId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): GameSession | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.gameId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: GameSession) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: GameSession) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: GameSession) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: GameSession) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: GameSession, newRow: GameSession) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: GameSession, newRow: GameSession) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
