// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type GameSession = {
  gameId: number,
  gameName: string | undefined,
  isActive: boolean,
  availableFieldIds: number[] | undefined,
};

/**
 * A namespace for generated helper functions.
 */
export namespace GameSession {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("gameId", AlgebraicType.createU32Type()),
      new ProductTypeElement("gameName", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("isActive", AlgebraicType.createBoolType()),
      new ProductTypeElement("availableFieldIds", AlgebraicType.createOptionType(AlgebraicType.createArrayType(AlgebraicType.createU32Type()))),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: GameSession): void {
    GameSession.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): GameSession {
    return GameSession.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


