// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type PlayerBingoCard = {
  cardId: string,
  playerSteamId: string,
  gameId: number,
  assignedFieldIds: number[],
};

/**
 * A namespace for generated helper functions.
 */
export namespace PlayerBingoCard {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("cardId", AlgebraicType.createStringType()),
      new ProductTypeElement("playerSteamId", AlgebraicType.createStringType()),
      new ProductTypeElement("gameId", AlgebraicType.createU32Type()),
      new ProductTypeElement("assignedFieldIds", AlgebraicType.createArrayType(AlgebraicType.createU32Type())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: PlayerBingoCard): void {
    PlayerBingoCard.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): PlayerBingoCard {
    return PlayerBingoCard.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


